### ISSUE TITLE
Inconsistent date formats in Composer map

### ISSUE THREAD

**Issue by jasonleeubc** [polyrhythm-project/polyrhythm-maps#16]
For birth/death dates, the format is presented inconsistently. For example, some dates are shown as dd-MMM-yy, while some others are shown in dd-MMMMM-yyyy. Investigation is needed to see where this inconsistency came from.

**Comment by jasonleeubc** [comment]
Conversion for dates went wrong when the csv file was imported into QGIS. The dates are now stored as strings in the javascript files. I can manually change the date formats. 

@epoudrier: What is the preferred format for birth/death dates? In the kern files we use the yyyy/mm/dd (e.g., 2023/03/21) for the date of editing. I think that's what Craig prefers.

**Comment by craigsapp** [comment]
> For birth/death dates, the format is presented inconsistently. For example, some dates are shown as dd-MMM-yy, while some others are shown in dd-MMMMM-yyyy. Investigation is needed to see where this inconsistency came from.

One suspect is that spreadsheets like to autoformat dates.  So some of them may have been adjusted by one automatic parsing or another.

> Conversion for dates went wrong when the csv file was imported into QGIS. The dates are now stored as strings in the javascript files. I can manually change the date formats.

And that seems to confirm the problem.

> @epoudrier: What is the preferred format for birth/death dates? In the kern files we use the yyyy/mm/dd (e.g., 2023/03/21) for the date of editing. I think that's what Craig prefers.

Yes, Humdrum uses `yyyy/mm/dd` which is good.

A good alternative is ISO dates:

> The ISO standard takes a general-to-specific approach for its date formats: The year comes first, followed by the month and then by the day of the month, with most elements represented as numerical values. For example, the ISO representation for July 15, 2022 is either 20220715 or 2022-07-15.

So `yyyy-mm-dd` or `yyyymmdd` (the second one is less likely to be messed up by spreadsheets).

**Comment by epoudrier** [comment]
My preference for the maps is how it is done on the FDS master: dd-mmm-yyyy
For example: 05-Mar-1874
