### ISSUE TITLE
New colours for composers map

### ISSUE THREAD

**Issue by ect123** [polyrhythm-project/polyrhythm-maps#24]
The composers mp uses some colours that might need to be restyled to be colour-blind friendly. I've used ColorBrewer to get hex or rgb codes for web accessible colours before and so it might be good to choose some from there. A qualitative, 3-class, scheme might work: https://colorbrewer2.org/#type=qualitative&scheme=Dark2&n=3

Additionally, I don't know if the marker clustering plugin used for the corpus map uses color blind friendly colours, but if they are, then I would suggest using those colors in the composers map if the intention is to have consistent styles for each of the maps.

**Comment by egrguric** [comment]
@jasonleeubc will explore colours after the basemaps are set.

**Comment by epoudrier** [comment]
@jasonleeubc add a colour legend on the map.

**Comment by craigsapp** [comment]
I set the color legend to a new issue #42, so this issue can be closed (@jasonleeubc has already updated the colors).
