### ISSUE TITLE
Update index.md

### ISSUE THREAD

**Issue by ect123** [polyrhythm-project/polyrhythm-maps#25]
The `index.md` file should be linked to the following pages:
- Corpus:[https://maps.polyrhythm.humdrum.org/corpus/corpus.html](https://maps.polyrhythm.humdrum.org/corpus/corpus.html)
- Timeline: [https://maps.polyrhythm.humdrum.org/timeline/timeline-1.html](https://maps.polyrhythm.humdrum.org/timeline/timeline-1.html) 
- Composers: [https://maps.polyrhythm.humdrum.org/composers/composers-birth-death/index.html](https://maps.polyrhythm.humdrum.org/composers/composers-birth-death/index.html)

The text "Premiers" should be changed to "Corpus"

**Comment by egrguric** [comment]
Update all of the links on index.md to reflect the correct new url path. Composers also needs to be updated to point to the .html file in Composers folder.

**Comment by epoudrier** [comment]
Newest maps will show when the pull requests are pushed.
