### ISSUE TITLE
New data for corpus and timeline maps

### ISSUE THREAD

**Issue by ect123** [polyrhythm-project/polyrhythm-maps#27]
The data for the corpus and timeline maps will need to be updated with the correct features. Once this data is produced, please convert the table into GeoJSON and send to @lilydemet and @Xilin-Wan. The current popup properties being used in the Corpus map are:
```
<b>Composer name: </b>"+feature.properties.composer_s_name+
          "<br><b>Work Title: </b>"+feature.properties.work_title+
          "<br><b>Genre: </b>"+feature.properties.genre+
          "<br><b>Sub Genre: </b>"+feature.properties.sub_genre+
          "<br><b>Composition year: </b>"+feature.properties.composition_year+
          "<br><b>Premiere Date: </b>"+feature.properties.premiere_date+
          "<br><b>Publication Year: </b>"+feature.properties.first_publication_year+
          "<br><b>Premiere Location: </b>"+feature.properties.venue_or_city+
          "<br><b>Performing Ensemble: </b>"+feature.properties.ensemble+
          "<br><b>Conductor: </b>"+feature.properties.conductor+
          "<br><b>soloists: </b>"+feature.properties.soloists+
          "<br><b>Corpus example: </b>"+feature.properties.example_no_2
```

**Comment by jasonleeubc** [comment]
@lilydemet @Xilin-Wan Here is the new data file. It includes all features specified on the readme of both the corpus and the timeline map. I have used the property names as stated above; note that the field "example_no_2" now contains ID numbers of ALL corpus examples for the particular work. 

There is one issue, though. For some of the premiere locations, we only have the name of the location, but not the geo-coordinates. Those coordinates are currently entered as 0, which will have to be corrected. Is there a good way to find the coordinates automatically? 

[corpus-timeline-newdata.geojson.zip](https://github.com/polyrhythm-project/polyrhythm-maps/files/11218624/corpus-timeline-newdata.geojson.zip)

**Comment by lilydemet** [comment]
@epoudrier @jasonleeubc Have you checked whether the lat/long exists for all premiere locations in prior datasets? If the coordinates do not exist in the dataset then the map function cannot render them geospatially. 

Also, when the dataset is finalized, please unzip the file and replace the contents of corpus.js with the updated data. The current maps and code documentation all refer to corpus.js as the corpus dataset and reconfiguring source links presents many opportunities for error.

**Comment by jasonleeubc** [comment]
@lilydemet In the previous dataset that is incomplete, all premieres locations have their lat/long values. But we are missing those values for some newly added locations in the updated dataset.

**Comment by lilydemet** [comment]
@jasonleeubc This is an issue I believe must be sorted out on your team's end. I suggest running a query in the updated dataset to see how many premieres lack coodinate values. Depending on that you could cross reference with the new dataset and programmatically or manually populate the fields.

**Comment by egrguric** [comment]
@jasonleeubc will update missing values for 30 null values manually.

**Comment by Xilin-Wan** [comment]
@jasonleeubc After you finish updating missing values and correcting the date format, please also update it in the corpus.js file, so the map will automatically update the data itself.

**Comment by jasonleeubc** [comment]
@Xilin-Wan @lilydemet I have updated the data set and created pull requests for corpus.geojson and corpus.js. Please check.

**Comment by Xilin-Wan** [comment]
> @Xilin-Wan @lilydemet I have updated the data set and created pull requests for corpus.geojson and corpus.js. Please check.

Hi, Jason. I just checked and I think it worked well. Thank you for updating the data, we can merge the pull request on the Thursday meeting.
