### ISSUE TITLE
Acknowledgment

### ISSUE THREAD

**Issue by epoudrier** [polyrhythm-project/polyrhythm-maps#31]
Evan suggested that it would be good to have a way to recognize the work that has been done by students on this project. I think it would be nice to also add staff. On the polyrhythm website (www.polyrhythm.humdrum.org), there is a People page that lists current members and past contributors. This would be the idea place to start. If there is a publication that also refers to the maps, you will be acknowleged for your work.

Could you please send me the necessary materials so I can post it on the website?

If you are planning to stay on the project for the summer, this is the format:
![Screenshot 2023-04-13 at 3 07 27 PM](https://user-images.githubusercontent.com/15526880/231894055-ee9577fe-a799-456d-80ad-034ad170838c.png)

If you are completing the work by the end of the month, this is the format:
![Screenshot 2023-04-13 at 3 07 55 PM](https://user-images.githubusercontent.com/15526880/231894117-a9b6406a-7818-4800-90f2-a950a97d1346.png)

**Comment by egrguric** [comment]
Include attribution in the GitHub repository Readme as well.

**Comment by egrguric** [comment]
- [ ] Take a screenshot w/ names and permissions of final Zoom call.

**Comment by egrguric** [comment]
@lilydemet and @ect123 need to submit brief bios before end of project.

**Comment by lilydemet** [comment]
Lily Demet, MA (Geography), Graduate Academic Assistant (Geographic Information and Technology), 2023

**Comment by epoudrier** [comment]
Done on website; needs to be re-published.
