### ISSUE TITLE
Map Information Text Box

### ISSUE THREAD

**Issue by craigsapp** [polyrhythm-project/polyrhythm-maps#42]
There should be a legend on the composer map that explains the colors of the dots: green is birth location and orange is death location.

Also there is whitespace on the right of the map, this would be a good location to give similar and/or extra information, such that the line between the green/orange dots links the birth/death locations.

An interesting thing to do in the future is to add blue does showing major locations where the composer worked.  These would be linked with lines in chronological order.

**Comment by ect123** [comment]
If possible, these would also be packaged up as different layers that could be toggled on and off using Leaflet layer controls: https://leafletjs.com/examples/layers-control/

**Comment by epoudrier** [comment]
The text box should also include information about how to use the map (esp. layer options).

**Comment by epoudrier** [comment]
See if we can move the menu of composers to the map (bottom right corner?). If not possible, see if the menu for visualization can be moved to the white space below the composers menu.

**Comment by ect123** [comment]
I think it might be a good idea to split this issue into at least two separate ones: one for the info box, and one for the restructuring the composer menu because they are independent of one another in the code. The info box can be done relatively easily as long as there is text for it.

**Comment by epoudrier** [comment]
Add link to premieres page when available (information box).
