### ISSUE TITLE
highlight the "clear filter" link on composers map

### ISSUE THREAD

**Issue by ect123** [polyrhythm-project/polyrhythm-maps#44]
It's not very clear how to clear the filter once you select a composer on the composer map. Potentially put red box around link or increasing size of text.

**Comment by epoudrier** [comment]
Another option is to have a colour button.

**Comment by jasonleeubc** [comment]
![image](https://github.com/polyrhythm-project/polyrhythm-maps/assets/89953048/43826806-07d1-4f3a-af7c-045e472dbc65)
