### ISSUE TITLE
Create layer for composers intermediary locations

### ISSUE THREAD

**Issue by ect123** [polyrhythm-project/polyrhythm-maps#47]
Some composers have lived in or visited some important places in their lifetime that wasn't a birth and death. A button in the white space that replaces the straight line with a multi line going through multiple locations. Also adds new point features for each of the locations.

**Comment by craigsapp** [comment]
Example use of Polyline to draw a line with multiple intermediate point:

<details>
<summary> Click example HTML code </summary>

```
<!DOCTYPE html>
<html>
  <head>
    <title>Leaflet Polyline Example</title>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/leaflet@1.7.1/dist/leaflet.css"
    />
    <style>
      #map {
        height: 400px;
      }
    </style>
  </head>
  <body>
    <div id="map"></div>

    <script src="https://cdn.jsdelivr.net/npm/leaflet@1.7.1/dist/leaflet.js"></script>
    <script>
      // Create a map instance
      var map = L.map("map").setView([51.505, -0.09], 13);

      // Add a tile layer to the map
      L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", {
        attribution: "Map data &copy; <a href='https://www.openstreetmap.org/'>OpenStreetMap</a> contributors",
      }).addTo(map);

      // Define an array of points
      var points = [
        [51.5, -0.09],
        [51.51, -0.1],
        [51.52, -0.12],
      ];

      // Create a polyline and add it to the map
      var polyline = L.polyline(points, { color: "red" }).addTo(map);
    </script>
  </body>
</html>
```

</details>

Screen shot:

<img width="1015" alt="Screenshot 2023-05-26 at 11 53 02 AM" src="https://github.com/polyrhythm-project/polyrhythm-maps/assets/3487289/8e163559-72ee-46fc-af82-d89c14fbd656">

**Comment by epoudrier** [comment]
Gather information about significant places of activity for each composer and add to geojason data file.

**Comment by epoudrier** [comment]
Jason done collecting location; next step is to in QGIS

**Comment by jasonleeubc** [comment]
An updated composer map is created with:
- intermediary locations for each composer
- options to show/hide each location type (birth/death/intermediary) and line type (from birth to death only or all locations)
- each location slightly adjusted to avoid overlapping of markers

The map is now accessible on https://maps.polyrhythm.humdrum.org/composers/testing_0724/#5/49.427/10.402.

**Comment by jasonleeubc** [comment]
To do @jasonleeubc :
1. Restrict zoom levels (levels 3 to 12) by changing the html code (line 45). 
2. Set the layer toggle in expanded form
3. Remove filter for "Map option"
4. Consider color and naming of the layers
