### ISSUE TITLE
Spiderfy for timeline map

### ISSUE THREAD

**Issue by ect123** [polyrhythm-project/polyrhythm-maps#48]
Some of the premieres overlap on the timeline map

**Comment by ect123** [comment]
This is the plugin that was used for marker clusters on the corpus map: https://github.com/Leaflet/Leaflet.markercluster. You can download these files and place them inside the cluster map directory to begin, using the documentation for the plugin to configure it t work with the timeline map data.

**Comment by bel28kent** [comment]
@ect123 I have created the branch 48-marker-clusters-for-timeline-map. I copied the Leaflet directory from corpus/ to timeline/. I also added some code from corpus.html to timeline-1.html. timeline-1.html now shows both marker clusters a la corpus map, but also balloons with slider like the original timeline map. Not sure how to resolve the two.

**Comment by ect123** [comment]
This is the plugin that might work better than the original one: https://github.com/ghybs/Leaflet.MarkerCluster.LayerSupport

**Comment by epoudrier** [comment]
Confirm that spiderfy can work independently from clusters, in which case, use only spiderfy to enhance accessing metadata for works with the same premiere venue.

**Comment by ect123** [comment]
The markers have been "separated" manually so that they don't actually overlap, but a user would need to zoom in to high zoom levels to see them. @epoudrier to make a note of this in the user information.

**Comment by epoudrier** [comment]
Spidery is not interact well with slider function, so we decided to not go in that direction.
