### ISSUE TITLE
Map Information Text Box for corpus map

### ISSUE THREAD

**Issue by epoudrier** [polyrhythm-project/polyrhythm-maps#56]
The map should include a legend and description of contents for users.

**Comment by ect123** [comment]
This would be a collapsible <div> in the right side of the map doc, and include information to the user: 
- this map displays the premiere locations of the works and the corpus. Blue pins represent a single work and colored numbers represent clusters of works. Click on the clusters to zoom in to the works in that area, and click on the blue markers to view more information about the work.
- If you want to learn more about these composers, see https://polyrhythm.humdrum.org/
- About the project

**Comment by epoudrier** [comment]
@ect123 Here are the texts for the information text boxes (feel free to edit typos!):
Corpus Map

This map displays the corpus source works by premiere location. Blue pins represent a single work and coloured shapes represent clusters of works. If the premiere venue is known, the blue pin marks the premiere venue. If the premiere venue is unknown, the blue pin is placed within the city limits. If the premiere city is unknown, the blue pin is placed within the capital city limits of the premiere country.

The default view includes all premiere locations for the corpus. Click on clusters to zoom in to the works in that area, and click on the blue markers to view more information about the work.

If you want to search the corpus and the analysis tools, see: https://polyrhythm.humdrum.org/
If you want to learn more about this project, see: https://polyrhythm.humdrum.org/about/

Note that there are [number] works that are not featured because the premiere location is unknown.

Composers Map

This map displays the life path of the composers featured in the corpus. Green dots represent birth place, red dots represent death place, and purple dots represent significant places of residence in the composers’ lifetime. Click on the dots to view more information about this location.

The default view includes all composers and locations connected by lines. Select viewing option by clicking the boxes of the overlay menu. Select one of more composers for display using the right side list. The composers’ list is organized alphabetically by last name. To select one composer, click on the composer’s name. To select a range of composers, click on the first composer in the range, hold shift, and then click on the last composer in the range. To select a number of non-adjacent composers, click on one composer name, hold command, and then click on the other composer(s) name(s).

If you want to learn more about these composers, see https://polyrhythm.humdrum.org/composers/
If you want to learn more about this project, see: https://polyrhythm.humdrum.org/about/

Timeline Map

This map displays the corpus source works by premiere location and year. Blue pins represent a single work. If the premiere venue is known, the blue pin marks the premiere venue. If the premiere venue is unknown, the blue pin is placed within the city limits. If the premiere city is unknown, the blue pin is placed within the capital city limits of the premiere country.

The default view includes all premiere locations for the corpus. Select a time range with the slider in the bottom left of the map. Click on the blue markers to view more information about the work premiere. For cities that featured a larges number of works, zoom in to view individual blue markers.

If you want to search the work premieres, see: [to be designed]
If you want to learn more about this project, see: https://polyrhythm.humdrum.org/about/

Note that there are [number] works for which the premiere year is unknown, and there are [number] works that are not featured because the premiere location is unknown.
