### ISSUE TITLE
Pop-up formatting

### ISSUE THREAD

**Issue by epoudrier** [polyrhythm-project/polyrhythm-maps#57]
Pop-up order and headings need to be reviewed and edited.

**Comment by jasonleeubc** [comment]
1. Applied title case to all pop-up headings
2. Added optional plural "(s)" to relevant headings
3. Rearranged order of fields to group together premiere info
4. Removed redundant words "name" and "title" from field headings.

**Comment by jasonleeubc** [comment]
The issue of missing spaces after commas (e.g. "Bartók,Béla" instead of "Bartók, Béla") seems to have arisen from the data source. These data fields are already missing the space in the FDS master. @epoudrier

**Comment by epoudrier** [comment]
Yes, because this us the formatting protocol in that spreadsheet. You need
to add them to the premières spreadsheet. You could try a find and replace.
Then you will need to double check.

**Comment by jasonleeubc** [comment]
Added missing spaces after commas in conductor/soloist names.
