### ISSUE TITLE
Timline map on load values

### ISSUE THREAD

**Issue by ect123** [polyrhythm-project/polyrhythm-maps#66]
set min and max value on load for the timeline map

**Comment by craigsapp** [comment]
Implemented with commit https://github.com/polyrhythm-project/polyrhythm-maps/commit/aa133fa3a358685d013d5fd7904861a4cd03f2bb

View when loading the timeline map now includes all premier points:

<img width="1276" alt="Screenshot 2023-09-13 at 21 31 34" src="https://github.com/polyrhythm-project/polyrhythm-maps/assets/3487289/b41955c9-b8eb-4023-a364-893cfa782b2d">

Difficult to control, but is basically working as desired now.   Required access to the HTML code for the slider:


```javascript
let minYear = 1877;
let maxYear = 1973;
var sliderElement = document.querySelector('#leaflet-slider');
sliderElement.value = minYear + ',' + maxYear;

var element1 = sliderElement.querySelector("div.ui-slider-range");
var element2 = sliderElement.querySelector("a.ui-corner-all");

element1.style.left = "100%";
element2.style.left = "100%";

sliderElement.dispatchEvent(new Event('change'));
```
