### ISSUE TITLE
Default sizing for composers map and menu

### ISSUE THREAD

**Issue by epoudrier** [polyrhythm-project/polyrhythm-maps#69]
The current default size of the composers map does not show the full range of locations. When zooming out to see, the composers menu font gets too small to read:
<img width="1256" alt="Screenshot 2023-09-14 at 10 15 25 AM" src="https://github.com/polyrhythm-project/polyrhythm-maps/assets/15526880/5e20a8c9-8e08-4b46-a5c9-f96f00109016">

**Comment by craigsapp** [comment]
The map resizing should be done with the +/- button on the top left side of the map, not with command-+/- to zoom in/out on the page (i.e., the text fonts will remain constant when zooming in on the map).

<img width="1230" alt="Screenshot 2023-09-14 at 12 41 09" src="https://github.com/polyrhythm-project/polyrhythm-maps/assets/3487289/751f522f-05c8-4cfc-9a59-259e8647453e">

Note the new final URL for the composers map:

https://maps.polyrhythm.humdrum.org/composers
