### ISSUE TITLE
Create GeoJSONs for each set of data

### ISSUE THREAD

**Issue by ect123** [polyrhythm-project/polyrhythm-maps#8]
We will need to convert the existing csv data that was used for the original heatmap and the timeline maps into geoJSON. The geoJSON can be created in a number of ways but I would recommend using QGIS. 

CSV data can be pulled into QGIS using the steps indicated here (although this might be a different version of QGIS than you have): https://www.qgistutorials.com/en/docs/importing_spreadsheets_csv.html

Save the features as geoJSON with a short filename (example: `timeline-locations.geojson` and `heatmap-locations.geojson`) in each map's directory.

**Comment by jasonleeubc** [comment]
I have created the geoJSON files for each of the three maps and uploaded the files in the corresponding folders. Please check and see if everything is alright.
