### ISSUE TITLE
Swap in Stamen Toner Lite basemap for composer map

### ISSUE THREAD

**Issue by ect123** [polyrhythm-project/polyrhythm-maps#9]
Stamen Designs offers their base map tile sets for use free-of-charge, and Toner-Lite is a great option for a background: http://maps.stamen.com/toner-lite/#12/37.7706/-122.3782.

To use this base map in the composers map, we'll need to swap out the existing Google Maps layer starting on line 71 of `/composers/composers-birth-death/index.html`. The replacement variable should align with directions here: http://maps.stamen.com/#toner-lite/12/37.7706/-122.3782

The variable being used for the base map looks to be auto-generated from the QGIS2Web plugin and references the style of the layer (`layer_GoogleRoad_0`). After getting Toner-lite to work with the old variable, create a new variable like `toner-lite-layer` or something similar to indicate that's the layer.

**Comment by ect123** [comment]
Hey @jasonleeubc is this working on your end with the Toner Lite basemap? If so, I'll go ahead and close the issue.

**Comment by jasonleeubc** [comment]
Yes, the updated html file works on my end with the Toner Lite basemap.
